name: Production Environment CI/CD

on:
  push:
    branches:
      - main

jobs:
  lint_prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci --ignore-scripts
      - run: npm run lint

      - name: 🔨 Build Project
        run: npm run build

  deploy_prod:
    runs-on: ubuntu-latest
    needs: lint_prod

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 📂 Login to Clasp
        uses: namaggarwal/clasp-token-action@v0.0.1
        with:
          client-id: '1072944905499-vm2v2i5dvn0a0d2o4ca36i1vge8cvbn0.apps.googleusercontent.com'
          client-secret: 'v6V3fKV_zWU7iw1DrpO1rknX'
          refresh-token: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImNhYWJmNjkwODE5MTYxNmE5MDhhMTM4OTIyMGE5NzViM2MwZmJjYTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIxMDcyOTQ0OTA1NDk5LXZtMnYyaTVkdm4wYTBkMm80Y2EzNmkxdmdlOGN2Ym4wLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMTA3Mjk0NDkwNTQ5OS12bTJ2Mmk1ZHZuMGEwZDJvNGNhMzZpMXZnZThjdmJuMC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExMzAzNjA3ODEwODk0MDU4OTM5OSIsImhkIjoidXNwLmJyIiwiZW1haWwiOiJ2aXZhcy5tYXRoZXVzQHVzcC5iciIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiV2tiQXYxN05hS3laTV9zUUQ2OEtZQSIsImlhdCI6MTY2MzM4Mzg1NCwiZXhwIjoxNjYzMzg3NDU0fQ.oNyCS26ZRo3xPUnGKGEVU0sXw7iiSQo8i216qy6-XLSGfP48us93n9zBnQpDR1sYvHfC1ayFSN_Wnk3_I_NMUPPsO8ACkbYA_kJ0rXocwuTj5Ls44gK6hv3q4mQxlJ4xHNUARRV-_dPipO-hXQjvpPa9ij56-aPi7mL00CPginzAuvNyzZrZiJXck-mr-DsHKqLBWOIG9njooYtEKdMkOdqgmF4hA4P1Ez42v1Q1uYpDhNcIWUUhDo_xBk__tHsuH21t_eh3cLz7PLCN5p_f6bwXOzQBlqWdrZ7QXvQIXfa0rFjfSBZT2THzWVOBvzFYNQ1yUdoTzDjwfps3EpLfXg'

      - name: Deploy to Google Sheets
        env:
          SCRIPT_ID: '1VKgOtJrLCm2DR3zCn1HsoDulkrRFNBWqgG33Fo05zkMq2lkIzWdJkJAA'
          ENV: 'GITHUB'
        run: |
          npm ci --ignore-scripts
          npm run clasp
          npm run push
